notifications:
  email: false

env:
  global:
    - CIBW_TEST_REQUIRES=nose
    - CIBW_TEST_COMMAND="nosetests {project}/tests"
    - S3_BUCKET=pythonwheelhouse

matrix:
  include:
    - sudo: required
      services:
        - docker
    - os: osx

script:
  - |
    if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then
      python cibuildwheel osx --output-dir wheelhouse
    else
      python cibuildwheel linux --output-dir wheelhouse
    fi
  - ls wheelhouse/
  - pip install https://github.com/joerick/libcloud/archive/v1.5.0-s3fix.zip wheelhouse_uploader certifi
  - python -m wheelhouse_uploader upload --provider-name=S3_EU_WEST --local-folder wheelhouse $S3_BUCKET
