notifications:
  email: false

env:
  global:
    PACKAGE_NAME: pyinstrument_cext

matrix:
  include:
    - sudo: required
      services:
        - docker
      env: DOCKER_IMAGE=quay.io/pypa/manylinux1_x86_64
    - sudo: required
      services:
        - docker
      env: DOCKER_IMAGE=quay.io/pypa/manylinux1_i686
           PRE_CMD=linux32

install:
  - docker pull $DOCKER_IMAGE

script:
  - |
    docker run --rm -i -v `pwd`:/io $DOCKER_IMAGE $PRE_CMD /bin/bash << 'EOF'
      set -o errexit
      set -o xtrace
      cd /io

      for PYBIN in /opt/python/*/bin; do
        "${PYBIN}/pip" install -r dev-requirements.txt
        "${PYBIN}/pip" wheel . -w wheelhouse/
      done

      for whl in wheelhouse/*.whl; do
        auditwheel repair "$whl" -w wheelhouse
      done

      # Install packages and test
      for PYBIN in /opt/python/*/bin/; do
        "${PYBIN}/pip" install pyinstrument_cext --no-index -f ./wheelhouse
        (cd "$HOME"; "${PYBIN}/nosetests" pyinstrument_cext)
      done
    EOF
  - ls wheelhouse/