environment:
  global:
    CIBW_TEST_REQUIRES: nose
    CIBW_TEST_COMMAND: "nosetests {project}\\tests"
    S3_BUCKET: pythonwheelhouse

build_script:
  - pip install https://github.com/joerick/cibuildwheel/archive/master.zip
  - cibuildwheel --output-dir wheelhouse

after_build:
  - "pip install https://github.com/joerick/libcloud/archive/v1.5.0-s3fix.zip wheelhouse-uploader certifi"
  - "python -m wheelhouse_uploader upload --provider-name=S3_EU_WEST --local-folder wheelhouse %S3_BUCKET%"

artifacts:
  - path: "wheelhouse\\*.whl"
    name: Wheels
