environment:
  global:
    # SDK v7.0 MSVC Express 2008's SetEnv.cmd script will fail if the
    # /E:ON and /V:ON options are not enabled in the batch script intepreter
    # See: http://stackoverflow.com/a/13751649/163740
    CMD_IN_ENV: "cmd /E:ON /V:ON /C .\\appveyor\\run_with_env.cmd"

  matrix:
    - PYTHON: C:\Python27
    - PYTHON: C:\Python27-x64
    - PYTHON: C:\Python33
    - PYTHON: C:\Python33-x64
    - PYTHON: C:\Python34
    - PYTHON: C:\Python34-x64
    - PYTHON: C:\Python35
    - PYTHON: C:\Python35-x64
    - PYTHON: C:\Python36

install:
  - ECHO "Filesystem root:"
  - ps: "ls \"C:/\""

  - ECHO "Installed SDKs:"
  - ps: "ls \"C:/Program Files/Microsoft SDKs/Windows\""

  # Prepend newly installed Python to the PATH of this build
  - "SET PATH=%PYTHON%;%PYTHON%\\Scripts;%PATH%"

  # Check that we have the expected version and architecture for Python
  - "python --version"
  - "python -c \"import struct; print(struct.calcsize('P') * 8)\""

  # Upgrade to the latest version of pip to avoid it displaying warnings
  # about it being out of date.
  - "pip install --disable-pip-version-check --user --upgrade pip"

  # Install the wheel package for building wheels
  - "pip install wheel"

build_script:
  # Build the wheel
  - "%CMD_IN_ENV% python -m pip wheel . -w wheelhouse"

test_script:
  # Run the tests using the package installed from wheel
  - "%PYTHON%/Python.exe -m pip install nose"
  - "%PYTHON%/Python.exe -m pip install pyinstrument_cext --no-index -f wheelhouse"
  - cd C:\
  - "%PYTHON%/Scripts/nosetests %APPVEYOR_BUILD_FOLDER%\\tests"

artifacts:
  - path: "wheelhouse\\*.whl"
    name: Wheels

deploy:
  description: ''
  provider: GitHub
  auth_token: $(GH_TOKEN)
  prerelease: true
  on:
    appveyor_repo_tag: true

